/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import type { AppLangCode } from './lang';

export type UIStrings = {
  tellMeStory: string;
  whoInStory: string;
  whoInStoryPlaceholder: string;
  ageGapSmall: string;
  younger: string;
  older: string;
  balance: string;
  orCustomize: string;
  addChild: string;
  childNamePlaceholder: string;
  ageLabel: string;
  makeHero: string;
  addButton: string;
  leaveEmptyHero: string;
  ageGapBig: string;
  ageGapChooseFocus: string;
  chooseFocus: string;
  createStory: string;
  weaving: string;
  loading1: string;
  loading2: string;
  loading3: string;
  loading4: string;
  loading5: string;
  appName: string;
  onboardingTitle: string;
  onboardingSubtitle: string;
  startDreaming: string;
  skip: string;
  languageLabel: string;
  upgrade: string;
  settings: string;
  createHero: string;
  createHeroSub: string;
  continueReading: string;
  continueReadingSub: string;
  enchantedCollections: string;
  noCollectionStories: string;
  yourFavorites: string;
  viewAll: string;
  library: string;
  librarySub: string;
  noLibraryStories: string;
  favoritesTitle: string;
  favoritesSub: string;
  noFavorites: string;
  profile: string;
  storiesSaved: string;
  storyLanguageLabel: string;
  backHome: string;
  settingsTitle: string;
  settingsLanguageHint: string;
  back: string;
  howWasDream: string;
  dreamBridgeTitle: string;
  rateThankYou: string;
  rateMagic: string;
  sleepTimer: string;
  reset: string;
  play: string;
  linkCopied: string;
  // Theme labels
  themeTitle: string;
  themeMagic: string;
  themeMagicDesc: string;
  themeNature: string;
  themeNatureDesc: string;
  themeWisdom: string;
  themeWisdomDesc: string;
  themeEmotions: string;
  themeEmotionsDesc: string;
  themeMoral: string;
  themeMoralDesc: string;
  themeModern: string;
  themeModernDesc: string;
  themeDaily: string;
  themeDailyDesc: string;
  // Length labels
  storyLength: string;
  lengthKiss: string;
  lengthKissDesc: string;
  lengthBedtime: string;
  lengthBedtimeDesc: string;
  lengthAdventure: string;
  lengthAdventureDesc: string;
  // Mode labels
  storyMode: string;
  modeNormal: string;
  modeNormalDesc: string;
  modeInteractive: string;
  modeInteractiveDesc: string;
  // New feature strings
  regenerate: string;
  sequel: string;
  sequelDesc: string;
  deleteStory: string;
  confirmDeleteMsg: string;
  cancel: string;
  errorGenerating: string;
  errorNetwork: string;
  tryAgain: string;
  sleepTimerSet: string;
  sleepTimerOff: string;
  minutesShort: string;
  choosePath: string;
  pathA: string;
  pathB: string;
  exportStory: string;
  storyExported: string;
  quietMode: string;
  // Auth
  signIn: string;
  signInGoogle: string;
  signInAnon: string;
  signOutLabel: string;
  syncCloud: string;
  // Kids
  myKids: string;
  myKidsDesc: string;
  addKid: string;
  noKidsYet: string;
  storiesHeard: string;
  selectAvatar: string;
  // Paywall
  upgradeTitle: string;
  upgradeDesc: string;
  freePlan: string;
  freePlanDesc: string;
  premiumPlan: string;
  premiumPlanDesc: string;
  storiesLeft: string;
  upgradeNow: string;
  // Parent Dashboard
  parentDashboard: string;
  parentDashboardDesc: string;
  totalStories: string;
  totalListening: string;
  favoriteTheme: string;
  avgRating: string;
  weeklyActivity: string;
  noDataYet: string;
  // Bedtime Routine
  bedtimeRoutine: string;
  bedtimeRoutineDesc: string;
  startRoutine: string;
  routineMusic: string;
  routineStory: string;
  routineDreamBridge: string;
  routineLightsOut: string;
  // Audio
  ambientMusic: string;
  voicePiano: string;
  voiceNature: string;
  voiceLullaby: string;
  voiceNone: string;
  premiumVoice: string;
  browserVoice: string;
};

export const UI_STRINGS: Record<AppLangCode, UIStrings> = {
  en: {
    tellMeStory: 'Tell me a story now',
    whoInStory: "Who's in the story?",
    whoInStoryPlaceholder: 'Leave empty — AI will choose a hero',
    ageGapSmall: "We'll blend both ages into the story",
    younger: 'Younger',
    older: 'Older',
    balance: 'Balance',
    orCustomize: 'or customize',
    addChild: 'Add child',
    childNamePlaceholder: 'Child name',
    ageLabel: 'Age (1-12)',
    makeHero: 'Make them the story hero',
    addButton: 'Add',
    leaveEmptyHero: 'Leave empty — AI will choose a hero',
    ageGapBig:
      'Big age gap! Stories work differently for different ages. Who should we focus on?',
    ageGapChooseFocus: 'Choose a focus to continue.',
    chooseFocus: 'Choose a focus to continue.',
    createStory: 'Create Story',
    weaving: 'Weaving your story...',
    loading1: 'Finding the perfect world...',
    loading2: 'Meeting your heroes...',
    loading3: 'Building the adventure...',
    loading4: 'Adding a pinch of magic...',
    loading5: 'Writing the Dream Bridge...',
    appName: 'Dream Weaver',
    onboardingTitle: 'Dream Weaver',
    onboardingSubtitle: 'Choose your language — stories and the app will match.',
    startDreaming: 'Start Dreaming',
    skip: 'Skip',
    languageLabel: 'Language',
    upgrade: 'Upgrade',
    settings: 'Settings',
    createHero: 'Create a new story',
    createHeroSub: 'Let AI weave a tale just for you',
    continueReading: 'Continue Reading',
    continueReadingSub: 'Your last generated story',
    enchantedCollections: 'Your Stories',
    noCollectionStories: 'No saved stories yet. Create one!',
    yourFavorites: 'Your Favorites',
    viewAll: 'View all',
    library: 'Library',
    librarySub: 'All saved stories',
    noLibraryStories: 'No saved stories yet.',
    favoritesTitle: 'Your Favorites',
    favoritesSub: 'Stories you love.',
    noFavorites: 'No favorites yet.',
    profile: 'Profile',
    storiesSaved: 'Stories saved',
    storyLanguageLabel: 'Story language',
    backHome: 'Back to Home',
    settingsTitle: 'Settings',
    settingsLanguageHint: 'Language for the whole app and every story',
    back: 'Back',
    howWasDream: 'How was this dream?',
    dreamBridgeTitle: 'Dream Bridge',
    rateThankYou: 'Thank you for rating!',
    rateMagic: 'Pure magic!',
    sleepTimer: 'Sleep Timer',
    reset: 'Reset',
    play: 'Play',
    linkCopied: 'Link copied!',
    themeTitle: 'Choose a theme',
    themeMagic: 'Magic & Imagination',
    themeMagicDesc: 'Fantasy, magical worlds, adventures, superpowers',
    themeNature: 'Nature & Animals',
    themeNatureDesc: 'Talking animals, forests, seasons, the wild',
    themeWisdom: 'Wisdom & True Stories',
    themeWisdomDesc: 'Mythology, Buddhism, life stories',
    themeEmotions: 'Friendship & Feelings',
    themeEmotionsDesc: 'Fears, jealousy, confidence, friendship',
    themeMoral: 'Moral Choices',
    themeMoralDesc: 'Value dilemmas, wise fables',
    themeModern: "Today's World",
    themeModernDesc: 'School, tablets, friends, challenges',
    themeDaily: 'Daily Story',
    themeDailyDesc: 'A changing topic for each day',
    storyLength: 'Story length',
    lengthKiss: 'Goodnight Kiss',
    lengthKissDesc: '~500 words',
    lengthBedtime: 'Bedtime Story',
    lengthBedtimeDesc: '~1,500 words',
    lengthAdventure: 'A Whole Adventure',
    lengthAdventureDesc: '~2,500 words (chapters)',
    storyMode: 'Story mode',
    modeNormal: 'Regular Story',
    modeNormalDesc: 'A complete story from start to finish',
    modeInteractive: 'Interactive Story',
    modeInteractiveDesc: 'You choose what happens next',
    regenerate: 'Create another version',
    sequel: 'Continue this story',
    sequelDesc: 'Generate part 2',
    deleteStory: 'Delete story',
    confirmDeleteMsg: 'Delete this story? This cannot be undone.',
    cancel: 'Cancel',
    errorGenerating: 'Something went wrong creating your story. Please try again.',
    errorNetwork: 'No internet connection. Please check and try again.',
    tryAgain: 'Try again',
    sleepTimerSet: 'Sleep timer set',
    sleepTimerOff: 'Sleep timer off',
    minutesShort: 'min',
    choosePath: 'What happens next?',
    pathA: 'Path A',
    pathB: 'Path B',
    exportStory: 'Save as text',
    storyExported: 'Story saved!',
    quietMode: 'Quiet mode',
    signIn: 'Sign in',
    signInGoogle: 'Sign in with Google',
    signInAnon: 'Continue without account',
    signOutLabel: 'Sign out',
    syncCloud: 'Sync to cloud',
    myKids: 'My Kids',
    myKidsDesc: 'Manage child profiles',
    addKid: 'Add a child',
    noKidsYet: 'No profiles yet. Add your first child!',
    storiesHeard: 'stories heard',
    selectAvatar: 'Choose avatar',
    upgradeTitle: 'Unlock Dream Weaver',
    upgradeDesc: 'Unlimited stories, premium voices, and more',
    freePlan: 'Free',
    freePlanDesc: '2 stories per day',
    premiumPlan: 'Premium',
    premiumPlanDesc: 'Unlimited stories, premium voices, background music, no limits',
    storiesLeft: 'stories left today',
    upgradeNow: 'Upgrade now',
    parentDashboard: 'Parent Dashboard',
    parentDashboardDesc: 'Your child\'s story insights',
    totalStories: 'Total stories',
    totalListening: 'Listening time',
    favoriteTheme: 'Favorite theme',
    avgRating: 'Avg rating',
    weeklyActivity: 'This week',
    noDataYet: 'No data yet. Generate some stories!',
    bedtimeRoutine: 'Bedtime Routine',
    bedtimeRoutineDesc: 'Guided wind-down to sleep',
    startRoutine: 'Start routine',
    routineMusic: 'Calming music',
    routineStory: 'Storytime',
    routineDreamBridge: 'Dream Bridge',
    routineLightsOut: 'Lights out',
    ambientMusic: 'Background music',
    voicePiano: 'Soft piano',
    voiceNature: 'Nature sounds',
    voiceLullaby: 'Lullaby',
    voiceNone: 'None',
    premiumVoice: 'Premium voice',
    browserVoice: 'Standard voice',
  },
  he: {
    tellMeStory: 'ספר לי סיפור עכשיו',
    whoInStory: 'מי בסיפור?',
    whoInStoryPlaceholder: 'השאר ריק — הבינה המלאכותית תבחר גיבור',
    ageGapSmall: 'נשלב את שני הגילים בסיפור',
    younger: 'הצעיר',
    older: 'המבוגר',
    balance: 'איזון',
    orCustomize: 'או התאמה אישית',
    addChild: 'הוסף ילד',
    childNamePlaceholder: 'שם הילד',
    ageLabel: 'גיל (1-12)',
    makeHero: 'הפוך אותו לגיבור הסיפור',
    addButton: 'הוסף',
    leaveEmptyHero: 'השאר ריק — הבינה המלאכותית תבחר גיבור',
    ageGapBig: 'פער גילאים גדול! סיפורים עובדים אחרת לגילאים שונים. על מי להתמקד?',
    ageGapChooseFocus: 'בחרו מיקוד כדי להמשיך.',
    chooseFocus: 'בחרו מיקוד כדי להמשיך.',
    createStory: 'צור סיפור',
    weaving: 'אורגים את הסיפור שלך...',
    loading1: 'מוצאים את העולם המושלם...',
    loading2: 'פוגשים את הגיבורים...',
    loading3: 'בונים את ההרפתקה...',
    loading4: 'מוסיפים קמצוץ קסם...',
    loading5: 'כותבים את גשר החלומות...',
    appName: 'Dream Weaver',
    onboardingTitle: 'Dream Weaver',
    onboardingSubtitle: 'בחרו שפה — האפליקציה והסיפורים יהיו באותה שפה.',
    startDreaming: 'התחל לחלום',
    skip: 'דלג',
    languageLabel: 'שפה',
    upgrade: 'שדרוג',
    settings: 'הגדרות',
    createHero: 'צרו סיפור חדש',
    createHeroSub: 'תנו לבינה המלאכותית לסרוג סיפור בשבילכם',
    continueReading: 'המשך קריאה',
    continueReadingSub: 'הסיפור האחרון שנוצר',
    enchantedCollections: 'הסיפורים שלך',
    noCollectionStories: 'עדיין אין סיפורים שמורים. צרו אחד!',
    yourFavorites: 'המועדפים שלך',
    viewAll: 'הכל',
    library: 'ספרייה',
    librarySub: 'כל הסיפורים השמורים',
    noLibraryStories: 'עדיין אין סיפורים שמורים.',
    favoritesTitle: 'המועדפים שלך',
    favoritesSub: 'סיפורים שאהבת.',
    noFavorites: 'עדיין אין מועדפים.',
    profile: 'פרופיל',
    storiesSaved: 'סיפורים שמורים',
    storyLanguageLabel: 'שפת הסיפור',
    backHome: 'חזרה לבית',
    settingsTitle: 'הגדרות',
    settingsLanguageHint: 'שפה לכל האפליקציה ולכל סיפור',
    back: 'חזרה',
    howWasDream: 'איך היה החלום?',
    dreamBridgeTitle: 'גשר החלום',
    rateThankYou: 'תודה על הדירוג!',
    rateMagic: 'קסם טהור!',
    sleepTimer: 'טיימר שינה',
    reset: 'איפוס',
    play: 'נגן',
    linkCopied: 'הקישור הועתק!',
    themeTitle: 'בחרו נושא',
    themeMagic: 'קסם ודמיון',
    themeMagicDesc: 'פנטזיה, עולמות קסומים, הרפתקאות, כוחות על',
    themeNature: 'מהטבע והחיות',
    themeNatureDesc: 'חיות מדברות, יערות, עונות השנה, עולם החי',
    themeWisdom: 'חכמים וסיפורים אמיתיים',
    themeWisdomDesc: 'מיתולוגיה, בודהיזם, סיפורי חיים',
    themeEmotions: 'חברות ורגשות',
    themeEmotionsDesc: 'פחדים, קנאה, ביטחון עצמי, חברות',
    themeMoral: 'בחירה מוסרית',
    themeMoralDesc: 'דילמות ערכיות, משלים חכמים',
    themeModern: 'מהעולם של היום',
    themeModernDesc: 'בית ספר, טאבלטים, חברים, התמודדויות',
    themeDaily: 'סיפור יומי',
    themeDailyDesc: 'נושא משתנה לפי היום',
    storyLength: 'אורך הסיפור',
    lengthKiss: 'נשיקת לילה טוב',
    lengthKissDesc: '~500 מילים',
    lengthBedtime: 'סיפור לפני שינה',
    lengthBedtimeDesc: '~1,500 מילים',
    lengthAdventure: 'עולם שלם להרפתקה',
    lengthAdventureDesc: '~2,500 מילים (בפרקים)',
    storyMode: 'סוג סיפור',
    modeNormal: 'סיפור רגיל',
    modeNormalDesc: 'סיפור שלם מתחילה ועד הסוף',
    modeInteractive: 'סיפור אינטראקטיבי',
    modeInteractiveDesc: 'אתם בוחרים מה קורה הלאה',
    regenerate: 'צור גרסה אחרת',
    sequel: 'המשך הסיפור',
    sequelDesc: 'יצירת חלק 2',
    deleteStory: 'מחק סיפור',
    confirmDeleteMsg: 'למחוק את הסיפור? לא ניתן לשחזר.',
    cancel: 'ביטול',
    errorGenerating: 'משהו השתבש ביצירת הסיפור. נסו שוב.',
    errorNetwork: 'אין חיבור לאינטרנט. בדקו ונסו שוב.',
    tryAgain: 'נסה שוב',
    sleepTimerSet: 'טיימר שינה הופעל',
    sleepTimerOff: 'טיימר שינה כבוי',
    minutesShort: 'דק׳',
    choosePath: 'מה קורה עכשיו?',
    pathA: 'אפשרות א׳',
    pathB: 'אפשרות ב׳',
    exportStory: 'שמור כטקסט',
    storyExported: 'הסיפור נשמר!',
    quietMode: 'מצב שקט',
    signIn: 'התחברות',
    signInGoogle: 'התחברות עם Google',
    signInAnon: 'המשך בלי חשבון',
    signOutLabel: 'התנתקות',
    syncCloud: 'סנכרון לענן',
    myKids: 'הילדים שלי',
    myKidsDesc: 'ניהול פרופילי ילדים',
    addKid: 'הוסף ילד',
    noKidsYet: 'עדיין אין פרופילים. הוסיפו את הילד הראשון!',
    storiesHeard: 'סיפורים שנשמעו',
    selectAvatar: 'בחרו אווטאר',
    upgradeTitle: 'שחררו את Dream Weaver',
    upgradeDesc: 'סיפורים ללא הגבלה, קולות פרימיום, ועוד',
    freePlan: 'חינם',
    freePlanDesc: '2 סיפורים ביום',
    premiumPlan: 'פרימיום',
    premiumPlanDesc: 'סיפורים ללא הגבלה, קולות פרימיום, מוזיקת רקע, בלי גבולות',
    storiesLeft: 'סיפורים נותרו היום',
    upgradeNow: 'שדרגו עכשיו',
    parentDashboard: 'לוח בקרה להורים',
    parentDashboardDesc: 'תובנות על הסיפורים של ילדכם',
    totalStories: 'סה"כ סיפורים',
    totalListening: 'זמן האזנה',
    favoriteTheme: 'נושא מועדף',
    avgRating: 'דירוג ממוצע',
    weeklyActivity: 'השבוע',
    noDataYet: 'אין נתונים עדיין. צרו כמה סיפורים!',
    bedtimeRoutine: 'שגרת שינה',
    bedtimeRoutineDesc: 'הכנה מודרכת לשינה',
    startRoutine: 'התחל שגרה',
    routineMusic: 'מוזיקה מרגיעה',
    routineStory: 'זמן סיפור',
    routineDreamBridge: 'גשר החלום',
    routineLightsOut: 'כיבוי אורות',
    ambientMusic: 'מוזיקת רקע',
    voicePiano: 'פסנתר רך',
    voiceNature: 'צלילי טבע',
    voiceLullaby: 'שיר ערש',
    voiceNone: 'ללא',
    premiumVoice: 'קול פרימיום',
    browserVoice: 'קול רגיל',
  },
  es: {
    tellMeStory: 'Cuéntame un cuento ahora',
    whoInStory: '¿Quién está en el cuento?',
    whoInStoryPlaceholder: 'Déjalo vacío — la IA elegirá un héroe',
    ageGapSmall: 'Mezclaremos ambas edades en el cuento',
    younger: 'Más pequeño',
    older: 'Mayor',
    balance: 'Equilibrio',
    orCustomize: 'o personalizar',
    addChild: 'Añadir niño',
    childNamePlaceholder: 'Nombre del niño',
    ageLabel: 'Edad (1-12)',
    makeHero: 'Hacerlo héroe del cuento',
    addButton: 'Añadir',
    leaveEmptyHero: 'Déjalo vacío — la IA elegirá un héroe',
    ageGapBig:
      '¡Gran diferencia de edad! Los cuentos funcionan distinto. ¿En quién nos enfocamos?',
    ageGapChooseFocus: 'Elige un enfoque para continuar.',
    chooseFocus: 'Elige un enfoque para continuar.',
    createStory: 'Crear cuento',
    weaving: 'Tejiendo tu cuento...',
    loading1: 'Buscando el mundo perfecto...',
    loading2: 'Conociendo a tus héroes...',
    loading3: 'Construyendo la aventura...',
    loading4: 'Añadiendo una pizca de magia...',
    loading5: 'Escribiendo el Puente de los Sueños...',
    appName: 'Dream Weaver',
    onboardingTitle: 'Dream Weaver',
    onboardingSubtitle: 'Elige el idioma — la app y los cuentos coincidirán.',
    startDreaming: 'Empezar a soñar',
    skip: 'Omitir',
    languageLabel: 'Idioma',
    upgrade: 'Mejorar',
    settings: 'Ajustes',
    createHero: 'Crea tu propio cuento',
    createHeroSub: 'Deja que la IA teja un relato para ti',
    continueReading: 'Seguir leyendo',
    continueReadingSub: 'Tu último cuento generado',
    enchantedCollections: 'Tus cuentos',
    noCollectionStories: '¡Aún no hay cuentos guardados. Crea uno!',
    yourFavorites: 'Tus favoritos',
    viewAll: 'Ver todo',
    library: 'Biblioteca',
    librarySub: 'Todos los cuentos guardados',
    noLibraryStories: 'Aún no hay cuentos guardados.',
    favoritesTitle: 'Tus favoritos',
    favoritesSub: 'Cuentos que amas.',
    noFavorites: 'Aún no hay favoritos.',
    profile: 'Perfil',
    storiesSaved: 'Cuentos guardados',
    storyLanguageLabel: 'Idioma del cuento',
    backHome: 'Volver al inicio',
    settingsTitle: 'Ajustes',
    settingsLanguageHint: 'Idioma para toda la app y cada cuento',
    back: 'Volver',
    howWasDream: '¿Qué tal este sueño?',
    dreamBridgeTitle: 'Puente del sueño',
    rateThankYou: '¡Gracias por valorar!',
    rateMagic: '¡Pura magia!',
    sleepTimer: 'Temporizador',
    reset: 'Reiniciar',
    play: 'Reproducir',
    linkCopied: '¡Enlace copiado!',
    themeTitle: 'Elige un tema',
    themeMagic: 'Magia e Imaginación',
    themeMagicDesc: 'Fantasía, mundos mágicos, aventuras, superpoderes',
    themeNature: 'Naturaleza y Animales',
    themeNatureDesc: 'Animales parlantes, bosques, estaciones, vida silvestre',
    themeWisdom: 'Sabiduría e Historias Reales',
    themeWisdomDesc: 'Mitología, budismo, historias de vida',
    themeEmotions: 'Amistad y Sentimientos',
    themeEmotionsDesc: 'Miedos, celos, confianza, amistad',
    themeMoral: 'Elecciones Morales',
    themeMoralDesc: 'Dilemas de valores, fábulas sabias',
    themeModern: 'El Mundo de Hoy',
    themeModernDesc: 'Escuela, tabletas, amigos, desafíos',
    themeDaily: 'Cuento del Día',
    themeDailyDesc: 'Un tema diferente cada día',
    storyLength: 'Duración',
    lengthKiss: 'Beso de buenas noches',
    lengthKissDesc: '~500 palabras',
    lengthBedtime: 'Cuento para dormir',
    lengthBedtimeDesc: '~1.500 palabras',
    lengthAdventure: 'Una aventura completa',
    lengthAdventureDesc: '~2.500 palabras (capítulos)',
    storyMode: 'Tipo de cuento',
    modeNormal: 'Cuento normal',
    modeNormalDesc: 'Un cuento completo de principio a fin',
    modeInteractive: 'Cuento interactivo',
    modeInteractiveDesc: 'Tú eliges qué pasa después',
    regenerate: 'Crear otra versión',
    sequel: 'Continuar este cuento',
    sequelDesc: 'Generar parte 2',
    deleteStory: 'Eliminar cuento',
    confirmDeleteMsg: '¿Eliminar este cuento? No se puede deshacer.',
    cancel: 'Cancelar',
    errorGenerating: 'Algo salió mal al crear tu cuento. Inténtalo de nuevo.',
    errorNetwork: 'Sin conexión a internet. Verifica e inténtalo de nuevo.',
    tryAgain: 'Intentar de nuevo',
    sleepTimerSet: 'Temporizador activado',
    sleepTimerOff: 'Temporizador desactivado',
    minutesShort: 'min',
    choosePath: '¿Qué pasa después?',
    pathA: 'Camino A',
    pathB: 'Camino B',
    exportStory: 'Guardar como texto',
    storyExported: '¡Cuento guardado!',
    quietMode: 'Modo silencioso',
    signIn: 'Iniciar sesión',
    signInGoogle: 'Iniciar sesión con Google',
    signInAnon: 'Continuar sin cuenta',
    signOutLabel: 'Cerrar sesión',
    syncCloud: 'Sincronizar en la nube',
    myKids: 'Mis niños',
    myKidsDesc: 'Gestionar perfiles de niños',
    addKid: 'Añadir niño',
    noKidsYet: 'Sin perfiles. ¡Añade tu primer niño!',
    storiesHeard: 'cuentos escuchados',
    selectAvatar: 'Elegir avatar',
    upgradeTitle: 'Desbloquea Dream Weaver',
    upgradeDesc: 'Cuentos ilimitados, voces premium y más',
    freePlan: 'Gratis',
    freePlanDesc: '2 cuentos al día',
    premiumPlan: 'Premium',
    premiumPlanDesc: 'Cuentos ilimitados, voces premium, música de fondo, sin límites',
    storiesLeft: 'cuentos restantes hoy',
    upgradeNow: 'Mejorar ahora',
    parentDashboard: 'Panel de padres',
    parentDashboardDesc: 'Estadísticas de cuentos de tu hijo',
    totalStories: 'Total de cuentos',
    totalListening: 'Tiempo de escucha',
    favoriteTheme: 'Tema favorito',
    avgRating: 'Valoración media',
    weeklyActivity: 'Esta semana',
    noDataYet: '¡Sin datos aún. Crea algunos cuentos!',
    bedtimeRoutine: 'Rutina nocturna',
    bedtimeRoutineDesc: 'Preparación guiada para dormir',
    startRoutine: 'Iniciar rutina',
    routineMusic: 'Música relajante',
    routineStory: 'Hora del cuento',
    routineDreamBridge: 'Puente del sueño',
    routineLightsOut: 'Apagar luces',
    ambientMusic: 'Música de fondo',
    voicePiano: 'Piano suave',
    voiceNature: 'Sonidos de la naturaleza',
    voiceLullaby: 'Nana',
    voiceNone: 'Ninguna',
    premiumVoice: 'Voz premium',
    browserVoice: 'Voz estándar',
  },
  fr: {
    tellMeStory: 'Raconte-moi une histoire',
    whoInStory: "Qui est dans l'histoire?",
    whoInStoryPlaceholder: "Laisse vide — l'IA choisira un héros",
    ageGapSmall: "Nous mélangerons les deux âges dans l'histoire",
    younger: 'Plus jeune',
    older: 'Plus âgé',
    balance: 'Équilibre',
    orCustomize: 'ou personnaliser',
    addChild: 'Ajouter un enfant',
    childNamePlaceholder: "Prénom de l'enfant",
    ageLabel: 'Âge (1-12)',
    makeHero: "En faire le héros de l'histoire",
    addButton: 'Ajouter',
    leaveEmptyHero: "Laisse vide — l'IA choisira un héros",
    ageGapBig:
      "Grand écart d'âge ! Les histoires ne sont pas les mêmes. Sur qui se concentrer ?",
    ageGapChooseFocus: 'Choisis un focus pour continuer.',
    chooseFocus: 'Choisis un focus pour continuer.',
    createStory: "Créer l'histoire",
    weaving: 'Nous tissons ton histoire...',
    loading1: 'Trouver le monde parfait...',
    loading2: 'Rencontrer tes héros...',
    loading3: "Construire l'aventure...",
    loading4: 'Ajouter une pincée de magie...',
    loading5: 'Écrire le Pont des Rêves...',
    appName: 'Dream Weaver',
    onboardingTitle: 'Dream Weaver',
    onboardingSubtitle: "Choisis la langue — l'app et les histoires suivront.",
    startDreaming: 'Commencer à rêver',
    skip: 'Passer',
    languageLabel: 'Langue',
    upgrade: 'Améliorer',
    settings: 'Réglages',
    createHero: 'Crée ta propre histoire',
    createHeroSub: "Laisse l'IA tisser un conte pour toi",
    continueReading: 'Continuer la lecture',
    continueReadingSub: 'Ta dernière histoire générée',
    enchantedCollections: 'Tes histoires',
    noCollectionStories: "Aucune histoire sauvegardée. Crée-en une !",
    yourFavorites: 'Tes favoris',
    viewAll: 'Tout voir',
    library: 'Bibliothèque',
    librarySub: 'Toutes les histoires sauvegardées',
    noLibraryStories: 'Aucune histoire sauvegardée.',
    favoritesTitle: 'Tes favoris',
    favoritesSub: 'Les histoires que tu aimes.',
    noFavorites: 'Pas encore de favoris.',
    profile: 'Profil',
    storiesSaved: 'Histoires sauvegardées',
    storyLanguageLabel: 'Langue des histoires',
    backHome: "Retour à l'accueil",
    settingsTitle: 'Réglages',
    settingsLanguageHint: "Langue pour toute l'app et chaque histoire",
    back: 'Retour',
    howWasDream: 'Comment était ce rêve ?',
    dreamBridgeTitle: 'Pont du rêve',
    rateThankYou: 'Merci pour la note !',
    rateMagic: 'Magie pure !',
    sleepTimer: 'Minuteur',
    reset: 'Réinitialiser',
    play: 'Lecture',
    linkCopied: 'Lien copié !',
    themeTitle: 'Choisis un thème',
    themeMagic: 'Magie et Imagination',
    themeMagicDesc: 'Fantaisie, mondes magiques, aventures, superpouvoirs',
    themeNature: 'Nature et Animaux',
    themeNatureDesc: 'Animaux parlants, forêts, saisons, vie sauvage',
    themeWisdom: 'Sagesse et Histoires Vraies',
    themeWisdomDesc: 'Mythologie, bouddhisme, récits de vie',
    themeEmotions: 'Amitié et Sentiments',
    themeEmotionsDesc: 'Peurs, jalousie, confiance, amitié',
    themeMoral: 'Choix Moraux',
    themeMoralDesc: 'Dilemmes de valeurs, fables sages',
    themeModern: "Le Monde d'Aujourd'hui",
    themeModernDesc: 'École, tablettes, amis, défis',
    themeDaily: 'Histoire du Jour',
    themeDailyDesc: 'Un thème différent chaque jour',
    storyLength: 'Longueur',
    lengthKiss: 'Bisou de bonne nuit',
    lengthKissDesc: '~500 mots',
    lengthBedtime: 'Histoire du soir',
    lengthBedtimeDesc: '~1 500 mots',
    lengthAdventure: 'Une aventure complète',
    lengthAdventureDesc: '~2 500 mots (chapitres)',
    storyMode: "Type d'histoire",
    modeNormal: 'Histoire normale',
    modeNormalDesc: 'Une histoire complète du début à la fin',
    modeInteractive: 'Histoire interactive',
    modeInteractiveDesc: 'Tu choisis la suite',
    regenerate: 'Créer une autre version',
    sequel: 'Continuer cette histoire',
    sequelDesc: 'Générer la partie 2',
    deleteStory: 'Supprimer',
    confirmDeleteMsg: 'Supprimer cette histoire ? Impossible de revenir en arrière.',
    cancel: 'Annuler',
    errorGenerating: "Un problème est survenu. Réessayez s'il vous plaît.",
    errorNetwork: 'Pas de connexion internet. Vérifiez et réessayez.',
    tryAgain: 'Réessayer',
    sleepTimerSet: 'Minuteur activé',
    sleepTimerOff: 'Minuteur désactivé',
    minutesShort: 'min',
    choosePath: 'Que se passe-t-il ensuite ?',
    pathA: 'Chemin A',
    pathB: 'Chemin B',
    exportStory: 'Enregistrer en texte',
    storyExported: 'Histoire enregistrée !',
    quietMode: 'Mode calme',
    signIn: 'Se connecter',
    signInGoogle: 'Se connecter avec Google',
    signInAnon: 'Continuer sans compte',
    signOutLabel: 'Se déconnecter',
    syncCloud: 'Synchroniser',
    myKids: 'Mes enfants',
    myKidsDesc: 'Gérer les profils enfants',
    addKid: 'Ajouter un enfant',
    noKidsYet: 'Pas encore de profils. Ajoutez votre premier enfant !',
    storiesHeard: 'histoires écoutées',
    selectAvatar: 'Choisir un avatar',
    upgradeTitle: 'Débloquer Dream Weaver',
    upgradeDesc: 'Histoires illimitées, voix premium et plus',
    freePlan: 'Gratuit',
    freePlanDesc: '2 histoires par jour',
    premiumPlan: 'Premium',
    premiumPlanDesc: 'Histoires illimitées, voix premium, musique de fond, sans limites',
    storiesLeft: 'histoires restantes aujourd\'hui',
    upgradeNow: 'Passer au premium',
    parentDashboard: 'Tableau de bord parents',
    parentDashboardDesc: 'Aperçu des histoires de votre enfant',
    totalStories: 'Total des histoires',
    totalListening: 'Temps d\'écoute',
    favoriteTheme: 'Thème préféré',
    avgRating: 'Note moyenne',
    weeklyActivity: 'Cette semaine',
    noDataYet: 'Pas encore de données. Créez des histoires !',
    bedtimeRoutine: 'Routine du coucher',
    bedtimeRoutineDesc: 'Accompagnement guidé vers le sommeil',
    startRoutine: 'Démarrer la routine',
    routineMusic: 'Musique apaisante',
    routineStory: 'Heure du conte',
    routineDreamBridge: 'Pont du rêve',
    routineLightsOut: 'Extinction des feux',
    ambientMusic: 'Musique d\'ambiance',
    voicePiano: 'Piano doux',
    voiceNature: 'Sons de la nature',
    voiceLullaby: 'Berceuse',
    voiceNone: 'Aucune',
    premiumVoice: 'Voix premium',
    browserVoice: 'Voix standard',
  },
  ar: {
    tellMeStory: 'احكِ لي قصة الآن',
    whoInStory: 'من في القصة؟',
    whoInStoryPlaceholder: 'اتركها فارغة — الذكاء الاصطناعي يختار بطلاً',
    ageGapSmall: 'سندمج العمرين في القصة',
    younger: 'الأصغر',
    older: 'الأكبر',
    balance: 'توازن',
    orCustomize: 'أو تخصيص',
    addChild: 'إضافة طفل',
    childNamePlaceholder: 'اسم الطفل',
    ageLabel: 'العمر (1-12)',
    makeHero: 'اجعله بطل القصة',
    addButton: 'إضافة',
    leaveEmptyHero: 'اتركها فارغة — الذكاء الاصطناعي يختار بطلاً',
    ageGapBig: 'فارق عمر كبير! القصص تختلف حسب العمر. على من نركز؟',
    ageGapChooseFocus: 'اختر التركيز للمتابعة.',
    chooseFocus: 'اختر التركيز للمتابعة.',
    createStory: 'إنشاء قصة',
    weaving: 'ننسج قصتك...',
    loading1: 'نجد العالم المثالي...',
    loading2: 'نلتقي بأبطالك...',
    loading3: 'نبني المغامرة...',
    loading4: 'نضيف رشة سحر...',
    loading5: 'نكتب جسر الحلم...',
    appName: 'Dream Weaver',
    onboardingTitle: 'Dream Weaver',
    onboardingSubtitle: 'اختر اللغة — التطبيق والقصص بنفس اللغة.',
    startDreaming: 'ابدأ الحلم',
    skip: 'تخطي',
    languageLabel: 'اللغة',
    upgrade: 'ترقية',
    settings: 'الإعدادات',
    createHero: 'اصنع قصتك',
    createHeroSub: 'دع الذكاء الاصطناعي ينسج حكاية لك',
    continueReading: 'متابعة القراءة',
    continueReadingSub: 'آخر قصة أُنشئت',
    enchantedCollections: 'قصصك',
    noCollectionStories: 'لا قصص محفوظة بعد. أنشئ واحدة!',
    yourFavorites: 'مفضلاتك',
    viewAll: 'الكل',
    library: 'المكتبة',
    librarySub: 'كل القصص المحفوظة',
    noLibraryStories: 'لا قصص محفوظة بعد.',
    favoritesTitle: 'مفضلاتك',
    favoritesSub: 'قصص تحبها.',
    noFavorites: 'لا مفضلات بعد.',
    profile: 'الملف',
    storiesSaved: 'قصص محفوظة',
    storyLanguageLabel: 'لغة القصة',
    backHome: 'الرئيسية',
    settingsTitle: 'الإعدادات',
    settingsLanguageHint: 'لغة التطبيق بأكمله وكل قصة',
    back: 'رجوع',
    howWasDream: 'كيف كان هذا الحلم؟',
    dreamBridgeTitle: 'جسر الحلم',
    rateThankYou: 'شكراً على التقييم!',
    rateMagic: 'سحر خالص!',
    sleepTimer: 'مؤقت النوم',
    reset: 'إعادة',
    play: 'تشغيل',
    linkCopied: 'تم نسخ الرابط!',
    themeTitle: 'اختر موضوعاً',
    themeMagic: 'سحر وخيال',
    themeMagicDesc: 'خيال، عوالم سحرية، مغامرات، قوى خارقة',
    themeNature: 'الطبيعة والحيوانات',
    themeNatureDesc: 'حيوانات ناطقة، غابات، فصول السنة، الحياة البرية',
    themeWisdom: 'حكمة وقصص حقيقية',
    themeWisdomDesc: 'أساطير، بوذية، قصص حياة',
    themeEmotions: 'صداقة ومشاعر',
    themeEmotionsDesc: 'مخاوف، غيرة، ثقة بالنفس، صداقة',
    themeMoral: 'اختيارات أخلاقية',
    themeMoralDesc: 'معضلات قيمية، حكايات حكيمة',
    themeModern: 'عالم اليوم',
    themeModernDesc: 'مدرسة، أجهزة، أصدقاء، تحديات',
    themeDaily: 'قصة اليوم',
    themeDailyDesc: 'موضوع مختلف كل يوم',
    storyLength: 'طول القصة',
    lengthKiss: 'قبلة ليلة سعيدة',
    lengthKissDesc: '~500 كلمة',
    lengthBedtime: 'قصة قبل النوم',
    lengthBedtimeDesc: '~1,500 كلمة',
    lengthAdventure: 'مغامرة كاملة',
    lengthAdventureDesc: '~2,500 كلمة (فصول)',
    storyMode: 'نوع القصة',
    modeNormal: 'قصة عادية',
    modeNormalDesc: 'قصة كاملة من البداية للنهاية',
    modeInteractive: 'قصة تفاعلية',
    modeInteractiveDesc: 'أنت تختار ماذا يحدث بعد ذلك',
    regenerate: 'أنشئ نسخة أخرى',
    sequel: 'أكمل هذه القصة',
    sequelDesc: 'إنشاء الجزء الثاني',
    deleteStory: 'حذف القصة',
    confirmDeleteMsg: 'حذف هذه القصة؟ لا يمكن التراجع.',
    cancel: 'إلغاء',
    errorGenerating: 'حدث خطأ أثناء إنشاء قصتك. حاول مرة أخرى.',
    errorNetwork: 'لا يوجد اتصال بالإنترنت. تحقق وحاول مرة أخرى.',
    tryAgain: 'حاول مرة أخرى',
    sleepTimerSet: 'تم ضبط المؤقت',
    sleepTimerOff: 'المؤقت متوقف',
    minutesShort: 'د',
    choosePath: 'ماذا يحدث بعد ذلك؟',
    pathA: 'المسار أ',
    pathB: 'المسار ب',
    exportStory: 'حفظ كنص',
    storyExported: 'تم حفظ القصة!',
    quietMode: 'الوضع الهادئ',
    signIn: 'تسجيل الدخول',
    signInGoogle: 'تسجيل الدخول بـ Google',
    signInAnon: 'المتابعة بدون حساب',
    signOutLabel: 'تسجيل الخروج',
    syncCloud: 'مزامنة السحابة',
    myKids: 'أطفالي',
    myKidsDesc: 'إدارة ملفات الأطفال',
    addKid: 'إضافة طفل',
    noKidsYet: 'لا ملفات بعد. أضف طفلك الأول!',
    storiesHeard: 'قصص سمعها',
    selectAvatar: 'اختر الصورة',
    upgradeTitle: 'افتح Dream Weaver',
    upgradeDesc: 'قصص غير محدودة، أصوات مميزة، والمزيد',
    freePlan: 'مجاني',
    freePlanDesc: 'قصتان في اليوم',
    premiumPlan: 'بريميوم',
    premiumPlanDesc: 'قصص غير محدودة، أصوات مميزة، موسيقى خلفية، بلا حدود',
    storiesLeft: 'قصص متبقية اليوم',
    upgradeNow: 'ترقية الآن',
    parentDashboard: 'لوحة الوالدين',
    parentDashboardDesc: 'رؤى قصص طفلك',
    totalStories: 'إجمالي القصص',
    totalListening: 'وقت الاستماع',
    favoriteTheme: 'الموضوع المفضل',
    avgRating: 'متوسط التقييم',
    weeklyActivity: 'هذا الأسبوع',
    noDataYet: 'لا بيانات بعد. أنشئ بعض القصص!',
    bedtimeRoutine: 'روتين النوم',
    bedtimeRoutineDesc: 'تحضير موجّه للنوم',
    startRoutine: 'بدء الروتين',
    routineMusic: 'موسيقى هادئة',
    routineStory: 'وقت القصة',
    routineDreamBridge: 'جسر الحلم',
    routineLightsOut: 'إطفاء الأنوار',
    ambientMusic: 'موسيقى خلفية',
    voicePiano: 'بيانو ناعم',
    voiceNature: 'أصوات الطبيعة',
    voiceLullaby: 'تهويدة',
    voiceNone: 'بدون',
    premiumVoice: 'صوت مميز',
    browserVoice: 'صوت عادي',
  },
  ja: {
    tellMeStory: 'おはなしして',
    whoInStory: 'おはなしに出てくるのは？',
    whoInStoryPlaceholder: '空欄のまま — AIがヒーローを選びます',
    ageGapSmall: '両方の年齢に合わせたおはなしにします',
    younger: '年下の子',
    older: '年上の子',
    balance: 'バランス',
    orCustomize: 'またはカスタマイズ',
    addChild: 'こどもを追加',
    childNamePlaceholder: 'こどもの名前',
    ageLabel: '年齢 (1-12)',
    makeHero: 'おはなしの主人公にする',
    addButton: '追加',
    leaveEmptyHero: '空欄のまま — AIがヒーローを選びます',
    ageGapBig: '年齢差が大きいです！おはなしは年齢によって変わります。どちらに合わせますか？',
    ageGapChooseFocus: 'フォーカスを選んでください。',
    chooseFocus: 'フォーカスを選んでください。',
    createStory: 'おはなしをつくる',
    weaving: 'おはなしを紡いでいます...',
    loading1: 'ぴったりの世界を探しています...',
    loading2: '主人公に出会っています...',
    loading3: '冒険を組み立てています...',
    loading4: '魔法をひとふり...',
    loading5: '夢の架け橋を書いています...',
    appName: 'Dream Weaver',
    onboardingTitle: 'Dream Weaver',
    onboardingSubtitle: '言語を選んでください — アプリとおはなしがその言語になります。',
    startDreaming: '夢をはじめよう',
    skip: 'スキップ',
    languageLabel: '言語',
    upgrade: 'アップグレード',
    settings: '設定',
    createHero: '新しいおはなしをつくる',
    createHeroSub: 'AIがあなただけの物語を紡ぎます',
    continueReading: '続きを読む',
    continueReadingSub: '最後に作ったおはなし',
    enchantedCollections: 'あなたのおはなし',
    noCollectionStories: 'まだおはなしがありません。つくりましょう！',
    yourFavorites: 'お気に入り',
    viewAll: 'すべて見る',
    library: 'ライブラリ',
    librarySub: '保存したすべてのおはなし',
    noLibraryStories: 'まだおはなしがありません。',
    favoritesTitle: 'お気に入り',
    favoritesSub: 'すきなおはなし。',
    noFavorites: 'まだお気に入りがありません。',
    profile: 'プロフィール',
    storiesSaved: '保存したおはなし',
    storyLanguageLabel: 'おはなしの言語',
    backHome: 'ホームに戻る',
    settingsTitle: '設定',
    settingsLanguageHint: 'アプリ全体とすべてのおはなしの言語',
    back: '戻る',
    howWasDream: 'このゆめはどうだった？',
    dreamBridgeTitle: '夢の架け橋',
    rateThankYou: '評価ありがとう！',
    rateMagic: '最高の魔法！',
    sleepTimer: 'おやすみタイマー',
    reset: 'リセット',
    play: '再生',
    linkCopied: 'リンクをコピーしました！',
    themeTitle: 'テーマを選ぼう',
    themeMagic: '魔法とファンタジー',
    themeMagicDesc: 'ファンタジー、魔法の世界、冒険、超能力',
    themeNature: '自然と動物',
    themeNatureDesc: 'おしゃべりな動物、森、季節、野生の世界',
    themeWisdom: '知恵と実話',
    themeWisdomDesc: '神話、仏教、人生の物語',
    themeEmotions: '友情と気持ち',
    themeEmotionsDesc: '不安、やきもち、自信、友情',
    themeMoral: '道徳的な選択',
    themeMoralDesc: '価値観のジレンマ、賢いたとえ話',
    themeModern: '今日の世界',
    themeModernDesc: '学校、タブレット、友だち、チャレンジ',
    themeDaily: '今日のおはなし',
    themeDailyDesc: '毎日ちがうテーマ',
    storyLength: 'おはなしの長さ',
    lengthKiss: 'おやすみのキス',
    lengthKissDesc: '約500語',
    lengthBedtime: 'おやすみのおはなし',
    lengthBedtimeDesc: '約1,500語',
    lengthAdventure: 'まるごと冒険',
    lengthAdventureDesc: '約2,500語（チャプター）',
    storyMode: 'おはなしのタイプ',
    modeNormal: 'ふつうのおはなし',
    modeNormalDesc: '最初から最後まで完結するおはなし',
    modeInteractive: 'インタラクティブ',
    modeInteractiveDesc: 'つぎになにが起きるか選ぼう',
    regenerate: 'もう一度つくる',
    sequel: 'このおはなしの続き',
    sequelDesc: 'パート2をつくる',
    deleteStory: 'おはなしを削除',
    confirmDeleteMsg: 'このおはなしを削除しますか？元に戻せません。',
    cancel: 'キャンセル',
    errorGenerating: 'おはなしの作成中にエラーが発生しました。もう一度お試しください。',
    errorNetwork: 'インターネットに接続されていません。確認してもう一度お試しください。',
    tryAgain: 'もう一度',
    sleepTimerSet: 'おやすみタイマーON',
    sleepTimerOff: 'おやすみタイマーOFF',
    minutesShort: '分',
    choosePath: 'つぎはどうなる？',
    pathA: 'みちA',
    pathB: 'みちB',
    exportStory: 'テキストで保存',
    storyExported: '保存しました！',
    quietMode: 'しずかモード',
    signIn: 'ログイン',
    signInGoogle: 'Googleでログイン',
    signInAnon: 'アカウントなしで続ける',
    signOutLabel: 'ログアウト',
    syncCloud: 'クラウドに同期',
    myKids: 'こどもたち',
    myKidsDesc: 'こどものプロフィール管理',
    addKid: 'こどもを追加',
    noKidsYet: 'まだプロフィールがありません。最初のこどもを追加しましょう！',
    storiesHeard: 'きいたおはなし',
    selectAvatar: 'アバターを選ぶ',
    upgradeTitle: 'Dream Weaverを解放',
    upgradeDesc: '無制限のおはなし、プレミアムボイス、その他',
    freePlan: '無料',
    freePlanDesc: '1日2つのおはなし',
    premiumPlan: 'プレミアム',
    premiumPlanDesc: '無制限のおはなし、プレミアムボイス、BGM、制限なし',
    storiesLeft: '今日のこりのおはなし',
    upgradeNow: 'アップグレード',
    parentDashboard: '保護者ダッシュボード',
    parentDashboardDesc: 'おこさまのおはなし統計',
    totalStories: 'おはなし合計',
    totalListening: 'リスニング時間',
    favoriteTheme: 'お気に入りテーマ',
    avgRating: '平均評価',
    weeklyActivity: '今週',
    noDataYet: 'まだデータがありません。おはなしを作りましょう！',
    bedtimeRoutine: 'おやすみルーティン',
    bedtimeRoutineDesc: 'ねむりへのガイド',
    startRoutine: 'ルーティン開始',
    routineMusic: 'リラックス音楽',
    routineStory: 'おはなしタイム',
    routineDreamBridge: '夢の架け橋',
    routineLightsOut: 'おやすみ',
    ambientMusic: 'BGM',
    voicePiano: 'やさしいピアノ',
    voiceNature: '自然の音',
    voiceLullaby: '子守唄',
    voiceNone: 'なし',
    premiumVoice: 'プレミアムボイス',
    browserVoice: '標準ボイス',
  },
};
